[package]
name = "lpips"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
burn.workspace = true
image.workspace = true

[lints]
workspace = true
